- MoreLinq/ToDelimitedString.g.cs
- MoreLinq/ToDelimitedString.g.tt
This builds on top of #107 in order to minimize diff lines.
> Mark non cls compliant methods as such

- MoreLinq.Test/NullArgumentTest.cs
> V2 null checks

- MoreLinq.Test/AtLeastTest.cs
- MoreLinq.Test/MoreLinq.Portable.Test.csproj
- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq/AtLeast.cs
- MoreLinq/MoreLinq.Portable.csproj
- MoreLinq/MoreLinq.csproj
If this is good for this method, I can implement the Exactly method, too.
> Implement AtLeast extension method #58

- MoreLinq.Test/FullGroupJoinTest.cs
- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq.sln
- MoreLinq/FullGroupJoin.cs
- MoreLinq/Lookup.cs
- MoreLinq/MoreLinq.Portable.csproj
- MoreLinq/MoreLinq.csproj
- MoreLinq/OrderPreservingLookup.cs
- MoreLinq/Properties/AssemblyInfo.cs
- lic/corefx/LICENSE
- pkg/morelinq.nuspec
> Add FullGroupJoin method

- MoreLinq.Test/TakeLastTest.cs
Noticed it was missing, implementation was already OK.
> Add test TakeLastDisposesSequenceEnumerator

- .travis.yml
This way [the badge text](https://github.com/morelinq/morelinq.github.io/blob/master/index.html#L25) becomes true :smile:
> travis: Build on mac too

- MoreLinq/Random.cs
- MoreLinq/project.json
> Better seeding for Random (addresses #65)

- MoreLinq.Test/Assert.cs
- MoreLinq.Test/AssertCountTest.cs
- MoreLinq.Test/AssertTest.cs
- MoreLinq.Test/AtLeastTest.cs
- MoreLinq.Test/BreakingFunc.cs
- MoreLinq.Test/BreakingSequence.cs
- MoreLinq.Test/Combinatorics.cs
- MoreLinq.Test/CountByTest.cs
- MoreLinq.Test/CurrentThreadCultureScope.cs
- MoreLinq.Test/FullGroupJoinTest.cs
- MoreLinq.Test/KeyValuePair.cs
- MoreLinq.Test/NestedLoopTest.cs
- MoreLinq.Test/NullArgumentTest.cs
- MoreLinq.Test/PadTest.cs
- MoreLinq.Test/Program.cs
- MoreLinq.Test/RandomSubsetTest.cs
- MoreLinq.Test/RandomTest.cs
- MoreLinq.Test/SampleData.cs
- MoreLinq.Test/ScanTest.cs
- MoreLinq.Test/Scope.cs
- MoreLinq.Test/SequenceReader.cs
- MoreLinq.Test/TestExtensions.cs
- MoreLinq.Test/TestingSequence.cs
- MoreLinq.Test/ToDataTableTest.cs
- MoreLinq.Test/TraceTest.cs
- MoreLinq.Test/TraverseTest.cs
- MoreLinq.Test/UnenumerableList.cs
- MoreLinq.Test/VerifiableEnumerator.cs
This PR reduces redundant syntax noise in test project.
> Redundant syntax in test project

- MoreLinq.Test/ScanRightTest.cs
- MoreLinq/ScanRight.cs
> implemented scanRight (issue #286)

- MoreLinq/FullGroupJoin.cs
- README.md
> FullGroupJoin: add overloads with default ValueTuple selector

- MoreLinq.Test/PadLeftTest.cs
- MoreLinq/PadLeft.cs
> Padleft (issue #312) 

- MoreLinq.Test/FullGroupJoinTest.cs
> FullGroupJoin test improvements

- .travis.yml
- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq.Test/NullArgumentTest.cs
- MoreLinq.Test/ToDataTableTest.cs
- MoreLinq/MoreLinq.csproj
- global.json
- msbuild.sh
- test.cmd
- test.sh
> Add .NET Standard 2.0 target (#343)

- .travis.yml
- travis-mono-test.sh
> Re-enable testing against .NET Core 1.0 on Travis CI

- appveyor.yml
> Use msys grep on AppVeryor for test validation

- MoreLinq/SkipLast.cs
Another step for #128 with ❤️ from @Milyli.
> Optimize SkipLast for IReadOnlyCollection

- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq.Test/SliceTest.cs
- MoreLinq.Test/UnenumerableReadOnlyList.cs
- MoreLinq/Slice.cs
> Optimize Slice for read-only lists (#128)

- MoreLinq.Test/ScanTest.cs
- MoreLinq/Scan.cs
> Fixes #392

- MoreLinq.Test/BreakingCollection.cs
- MoreLinq.Test/BreakingList.cs
As proposed in https://github.com/morelinq/MoreLINQ/pull/406#issuecomment-372410156. Rounds out the rest of #385 .
> Make BreakingList inherit from BreakingCollection

- MoreLinq/MoreLinq.csproj
reminding also that we changed signature of `MaxBy `and `MinBy`, and improved `Scan`.
> Updated release notes with CompareCount & Transpose

- MoreLinq.Test/PreScanTest.cs
It needs #447 merged on master to test has success.
> Used BreakingFunc on PreScanWithSingleElement test

- MoreLinq.Test/AggregateRightTest.cs
- MoreLinq.Test/TestExtensions.cs
- MoreLinq/AggregateRight.cs
Closing in on wrapping up #128!
After going back and forth, decided to use a closure for an indexer. We can hash out the pros/cons of that.
> Optimize AggregateRight for read-only lists #128

- MoreLinq.Test/ChooseTest.cs
- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq/Choose.cs
- MoreLinq/MoreLinq.csproj
- README.md
This PR is the implementation for `Choose` proposed in #358.
> Choose (some values) implementation

- MoreLinq.Test/RandomSubsetTest.cs
- MoreLinq/RandomSubset.cs
add a test that ensure random subset returns exactly the same elements of original sequence
> Test that RandomSubset returns original sequence elements

- MoreLinq.Test/ConcatTest.cs
- MoreLinq/Concat.cs
- README.md
> Drop Concat overload extending a single element (#494)

- MoreLinq.Test/WindowTest.cs
- MoreLinq/MoreLinq.csproj
- MoreLinq/Window.cs
- README.md
> Rename Windowed to Window & return windows as lists (#520)

- README.md
Added missing word 'hashset' with link to docs page
> Update ToHashSet description

- MoreLinq.Test/CountByTest.cs
- MoreLinq/CountBy.cs
> Fix CountBy to handle null keys

- MoreLinq/Experimental/Memoize.cs
> Use List for Memoize's cache (performance)

- MoreLinq/Scan.cs
Refactored Scan implementation to avoid repetitive code.
> Refactored Scan implementation

- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq.Test/ToDataTableTest.cs
- MoreLinq/Extensions.g.cs
- MoreLinq/MoreLinq.csproj
- MoreLinq/Scan.cs
- MoreLinq/ToDataTable.cs
- README.md
This PR prepares 3.1.1 patch release, which primarily contains the fix for #564.
> 3.1.1 patch release

- MoreLinq.Test/TestingSequence.cs
- MoreLinq.Test/WatchableEnumerator.cs
- MoreLinq/Move.cs
> Move iterates past end of sequence (issue #589)

- MoreLinq/EquiZip.cs
- MoreLinq/Extensions.g.cs
- MoreLinq/ZipLongest.cs
- MoreLinq/ZipShortest.cs
- README.md
This PR is a consolidation of PR #583, #584 & #585.
> Distinct docs for EquiZip & ZipShortest/Longest

- MoreLinq/Exclude.cs
- MoreLinq/Lead.cs
> Add missing using instruction in Exclude and Lead.

- README.md
Interleave actually only have one overload
> Update README.md : Interleave actually only have one overload

- MoreLinq/MoreLinq.csproj
Add missing method in project description
Mark Memoize as experimental.
> Update MoreLinq.csproj: Add missing method in project description

- MoreLinq.Test/SegmentTest.cs
- MoreLinq/Segment.cs
> Fix Segment to not call MoveNext past end of sequence

- MoreLinq.Test/OrderedMergeTest.cs
`OrderedMerge` is not tested yet.
This PR add tests for it.
> OrderedMerge: add tests

- MoreLinq.Test/AssertCountTest.cs
- MoreLinq.Test/BacksertTest.cs
- MoreLinq.Test/BatchTest.cs
- MoreLinq.Test/CartesianTest.cs
- MoreLinq.Test/ChooseTest.cs
- MoreLinq.Test/CompareCountTest.cs
- MoreLinq.Test/CountDownTest.cs
- MoreLinq.Test/EndsWithTest.cs
- MoreLinq.Test/EquiZipTest.cs
- MoreLinq.Test/FlattenTest.cs
- MoreLinq.Test/GroupAdjacentTest.cs
- MoreLinq.Test/InsertTest.cs
- MoreLinq.Test/InterleaveTest.cs
- MoreLinq.Test/MemoizeTest.cs
- MoreLinq.Test/MoveTest.cs
- MoreLinq.Test/PartitionTest.cs
- MoreLinq.Test/RepeatTest.cs
- MoreLinq.Test/SortedMergeTest.cs
- MoreLinq.Test/SplitTest.cs
- MoreLinq.Test/StartsWithTest.cs
- MoreLinq.Test/TakeLastTest.cs
- MoreLinq.Test/TransposeTest.cs
- MoreLinq.Test/WindowLeftTest.cs
- MoreLinq.Test/WindowRightTest.cs
- MoreLinq.Test/WindowTest.cs
- MoreLinq.Test/ZipLongestTest.cs
- MoreLinq.Test/ZipShortestTest.cs
This is a follow-on from PR #622 that addresses the unit tests.
> Replace using statements with declarations in tests

- appveyor.yml
The invocation of `grep` during a CI build on Windows:
```ps1
grep --extended-regexp '^[[:space:]]*using[[:space:]]+System\.Linq;' (dir -Recurse -File -Filter *Test.cs MoreLinq.Test)
```
causes a stream of missing file errors:
[00:00:52] grep : /usr/bin/grep: AcquireTest.cs: No such file or directory
[00:00:52] At line:1 char:1
[00:00:52] + grep --extended-regexp '^[[:space:]]*using[[:space:]]+System\.Linq;'  ...
[00:00:52] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:00:52]     + CategoryInfo          : NotSpecified: (/usr/bin/grep: ...le or directory:String) [], RemoteException
[00:00:52]     + FullyQualifiedErrorId : NativeCommandError
[00:00:52]  
[00:00:53] /usr/bin/grep
[00:00:53] :
[00:00:53]  
[00:00:53] AggregateRightTest.cs
[00:00:53] : 
[00:00:53] …
> Fix grep invocation on Windows CI build

- MoreLinq/Extensions.g.cs
- MoreLinq/ScanRight.cs
See issue https://github.com/morelinq/MoreLINQ/issues/795
> Doc update (+ instead of /)

- Directory.Build.props
This PR allows use of C# 10 across the project.
> Allow use of C# 10

- MoreLinq/AggregateRight.cs
- MoreLinq/ScanRight.cs
This PR replaces manual last index calculation with `[^1]` instead.
> Use end index "[^1]"

- MoreLinq/Sequence.cs
This PR rewrites an increment using `+=`.
> Use `+=` to increment

- Directory.Build.props
This PR allows use of C# 11 across the project.
> Allow use of C# 11

- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq/MoreLinq.csproj
- bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
This PR updates packages/dependencies to their latest versions.
> Update packages to latest versions

- MoreLinq.Test/PairwiseTest.cs
> Use testing sequence in `Pairwise` test

- MoreLinq/MoreLinq.csproj
This PR adds the read-me document to the NuGet package.
> Add read-me document to NuGet package

- MoreLinq/MoreLinq.csproj
- appveyor.yml
> Produce deterministic CI builds

- tools/dotnet-install.ps1
- tools/dotnet-install.sh
This PR updates the [.NET installation scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) to their latest versions.
> Update "dotnet-install" scripts

- MoreLinq.Test/UnfoldTest.cs
- MoreLinq/Unfold.cs
This PR rolls the fix for #990 into the latest development branch (`master`).
> Merge fix for #990 into master

- MoreLinq.Test/.editorconfig
- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq/MoreLinq.csproj
- bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
This PR updates all packages to their latest versions.
Pending:
> Update all packages to latest versions

- MoreLinq.Test/MoreLinq.Test.csproj
This PR updates test packages to their latest versions.
> Update test packages to latest versions

- appveyor.yml
This PR updates the Ubuntu image used on CI to use 18.04.
> Update Ubuntu image on CI to use 18.04

- MoreLinq.Test/Async/TestingAsyncSequence.cs
- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq/MoreLinq.csproj
- bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
This PR updates all packages to their latest versions.
> Update packages to their latest versions

- MoreLinq/MoreLinq.csproj
This PR bumps the version to 4.3.1.
> Bump version to 4.3.1

- .config/dotnet-tools.json
This PR updates all tools to their latest versions.
> Update all tools to their latest versions

- MoreLinq.Test/MoreLinq.Test.csproj
- MoreLinq.Test/Throws.cs
This PR updates all NUnit packages to their latest versions.
> Update NUnit packages to their latest versions

- MoreLinq.Test/AcquireTest.cs
- MoreLinq.Test/Async/MergeTest.cs
- MoreLinq.Test/BatchTest.cs
- MoreLinq.Test/EquiZipTest.cs
- MoreLinq.Test/TakeLastTest.cs
- MoreLinq.Test/ZipShortestTest.cs
This PR addresses more opportunities to use collection expressions in tests.
> Use collection expressions in tests

- Directory.Build.props
- MoreLinq/Experimental/Memoize.cs
- MoreLinq/Lock.cs
This PR enables the use of C# 13.
> Allow use of C# 13
