morelinq/MoreLINQ

MoreLinq.Test/MaxByTest.cs
MoreLinq.Test/MinByTest.cs
MoreLinq.Test/NullArgumentTest.cs
MoreLinq/CanBeNullAttribute.cs
MoreLinq/DistinctBy.cs
MoreLinq/ExceptBy.cs
MoreLinq/GroupAdjacent.cs
MoreLinq/MaxBy.cs
MoreLinq/MinBy.cs
MoreLinq/MoreLinq.Portable.csproj
MoreLinq/MoreLinq.csproj
MoreLinq/OrderedMerge.cs
MoreLinq/Split.cs
MoreLinq/ToDataTable.cs
MoreLinq/ToDelimitedString.cs
MoreLinq/ToDelimitedString.g.cs
MoreLinq/ToDelimitedString.g.tt
MoreLinq/ToHashSet.cs
MoreLinq/Trace.cs

Removes `[CanBeNull]` and adapts tests.
Changes `MaxBy`/`MinBy` to accept null for `IComparer<T>` and fix docs.
Fixes #111.

Null checks

---

MoreLinq/GroupAdjacent.cs

Do it inside the loop. Also, avoid allocating a new KeyValuePair element, as it is not needed.
On a simple naive test like `longList.GroupAdjacent(i => i.Key).Consume();`, it achieves a 30% performance improvement in my system. Real-World effect will probably be lower (as selector are more complicated and are not consumed in a tight loop), but I still think it is a worthwhile improvement.

GroupAdjacent: Do not use Select to project key and element

---

MoreLinq/EquiZip.cs

This PR adds the missing `<returns>` XmlDoc to the EquiZip methods with three and four inputs. Fixes #147

Add <returns> comment to EquiZip

---

MoreLinq.Test/GroupAdjacentTest.cs
MoreLinq/GroupAdjacent.cs

For parity with the GroupBy overloads
Fixes: #127

 GroupAdjacent: Add overloads that allow selecting the return enumerable type

---

MoreLinq.Test/EndsWithTest.cs
MoreLinq.Test/MoreLinq.Portable.Test.csproj
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/StartsWithTest.cs
MoreLinq/EndsWith.cs
MoreLinq/MoreLinq.Portable.csproj
MoreLinq/MoreLinq.csproj
MoreLinq/StartsWith.cs

Similar to `String.StartsWith()` and `.EndsWith()`, except on `IEnumerable<T>`. Can even take strings as arguments, as sequences of chars.
* Add MoreEnumerable.StartsWith()
* Add MoreEnumerable.EndsWith()
* Add 15 test cases for StartsWith
* Add 15 test cases for EndsWith
All tests run OK locally.
I tried to glance through and match the coding conventions, but let me know if you see anything that is off or test cases you would want to add.

Add StartsWith and EndsWith

---

README.md

As indicated by issue #179 some developers might not be aware of morelinq.github.io, which is why I added a mention of it in the README.md.

Added reference to Documentation in README.md

---

MoreLinq.Test/FoldTest.cs
MoreLinq.Test/MoreLinq.Test.xproj
MoreLinq/Fold.cs
MoreLinq/Fold.g.cs
MoreLinq/Fold.g.tt

Do not throw `Exception`, but rather `InvalidOperationException` instead.
Document exceptions thrown.

Fold: throw InvalidOperationException instead & document exceptions

---

MoreLinq.Test/ToLookupTest.cs
MoreLinq/MoreLinq.csproj
MoreLinq/ToLookup.cs
README.md

ToLookup overloads for key-value pairs & tuples of 2 (#274)

---

MoreLinq.Test/CountByTest.cs
MoreLinq/CountBy.cs

I discovered a bug when testing the function with the string "jaffer". 
The operator tell us that there is 2 chars j instead of 2 f.
Basically we forgot to set `index` when a new key is registered, what present us with a bug that appears in a specific scenario: when second occurrence of an element occurs immediately after first.

Fix bug on CountBy

---

MoreLinq.Test/ExcludeTest.cs

The tests were using sequences where all elements are equals, what dont let us to check if the right elements were exclude. 
So the tests were, in fact, only testing if the function had exclude the right number of elements.

Improve/Fix ExcludeTest

---

MoreLinq.Test/EvaluateTest.cs
MoreLinq/Evaluate.cs

Fixes: #151 
I ended up naming the function `Values` as that was mentioned by @atifaziz on #293 (which I think can also be closed if this is merged). I can rename back to `FromDelegates` or other name if `Values` is not appropriate. I thought about naming the method `Fabricate` or `Manufacture` (because the parameters are factories) but that feels a bit weird.

Add Evaluate function that evaluates a sequence of functions

---

MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq/MoreLinq.csproj

This PR is designed to address #280. It helps with type unification under .NET 4.7 by upgrading to [System.ValueTuple 4.4](https://www.nuget.org/packages/System.ValueTuple/4.4.0).

Upgrade System.ValueTuple package to 4.4

---

MoreLinq.Test/MoreLinq.Test.csproj

The _Live Unit Testing_ feature is available from Visual Studio 2017 update 15.3.
**NuGet packages added**
- _NUnit3TestAdapter_ because visual studio needs that for live testing to find the tests.
- _Microsoft.NET.Test.Sdk_ because live testing asked if it was installed - which implies it is required.
**Set the startup object explicitly in MoreLinq.Test**
- It was necessary to set the startup  object to be _MoreLinq.Test.Program_ because of additional possible start points created by one or other of the NuGet packages above.

Added additional nuget packages to enable live testing

---

MoreLinq/Fold.cs
MoreLinq/Fold.g.cs
MoreLinq/Fold.g.tt
MoreLinq/FullGroupJoin.cs
MoreLinq/MoreLinq.csproj
MoreLinq/Partition.cs
MoreLinq/ToDictionary.cs
MoreLinq/ToLookup.cs

This PR addresses #329.
Gone are also the `FUNC16` and `NO_VALUE_TUPLES` conditional symbols.

Drop .NET Framework 3.5 target/support

---

MoreLinq.Test/AssertCountTest.cs
MoreLinq.Test/BreakingSequence.cs
MoreLinq/AssertCount.cs

This PR addresses #364.
If the collection count is the value to be asserted then it is returned directly. Otherwise, a sequence is returned that will throw as soon as it is enumerated.

Fix AssertCount to be lazy for collections too

---

MoreLinq.Test/NullArgumentTest.cs
MoreLinq.Test/ToDelimitedStringTest.cs
MoreLinq/ToDelimitedString.cs
MoreLinq/ToDelimitedString.g.cs
MoreLinq/ToDelimitedString.g.tt

This PR addresses #229.
The overloads have been obsolete since [version 2.1](https://github.com/morelinq/MoreLINQ/releases/tag/v2.1.0).

Remove delimiter-less ToDelimitedString overloads

---

MoreLinq/Experimental/ExperimentalEnumerable.cs

This PR addresses #209.
Hope the warning in the document summary is LOUD AND CLEAR. 📢
If this turns out to be a very bad idea, it can be scratched in any _minor_ release.

Add namespace & type to house experimental work

---

MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/SequenceReader.cs
MoreLinq/EquiZip.cs
MoreLinq/FallbackIfEmpty.cs
MoreLinq/Interleave.cs
MoreLinq/Lag.cs
MoreLinq/Lead.cs
MoreLinq/MoreLinq.csproj
MoreLinq/Pad.cs
MoreLinq/PadStart.cs
MoreLinq/Partition.cs
MoreLinq/TagFirstLast.cs
MoreLinq/ZipLongest.cs
MoreLinq/ZipShortest.cs

This is to primarily help get rid of more syntactic redundancies, like:
- [Default literal expressions][default-literal-expressions] (`default`)
- [Inferred tuple element names][inferred-tuple-element-names]
[default-literal-expressions]: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#default-literal-expressions
[inferred-tuple-element-names]: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#inferred-tuple-element-names

Upgrade to C# 7.1

---

MoreLinq/Flatten.cs

This is a remnant of the time there was a `break` where today is `goto reloop;`.

Removed unnecessary validation for Disposing Sequence in Flatten operator

---

MoreLinq/TagFirstLast.cs

`TagFirstLast` was allocating (anonymous) objects for internal representations, _at least two per source element_! This PR reduces those allocations by using value tuples instead.

Use value tuples to reduce allocations in TagFirstLast

---

MoreLinq.Test/BreakingAction.cs
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/NestedLoopTest.cs
MoreLinq/NestedLoops.cs

changes:
- refactored `NestedLoop` to become lazy
- added `NestedLoopsIsLazy` test
- refactored tests considering lazy evaluation
- ~~added `TestNestedLoopConsumesSequenceLazily` test~~
- added `NestedLoopWithEmptySequence` test
- added `NestedLoopContainingZero` test
- added `NestedLoopWithLastElementNegative` test

Much simplified (lazy) NestedLoop implementation

---

MoreLinq.Test/CartesianTest.cs
MoreLinq.Test/ExcludeTest.cs
MoreLinq.Test/InterleaveTest.cs
MoreLinq.Test/MaxByTest.cs
MoreLinq.Test/MinByTest.cs
MoreLinq.Test/ScanTest.cs
MoreLinq.Test/SegmentTest.cs
MoreLinq.Test/SequenceTest.cs
MoreLinq.Test/SkipLastTest.cs
MoreLinq.Test/SkipUntilTest.cs
MoreLinq.Test/TakeEveryTest.cs
MoreLinq.Test/TakeLastTest.cs
MoreLinq.Test/UnfoldTest.cs
MoreLinq.Test/WindowedTest.cs

use a single approach to check empty sequences.
all current approaches
```c#
Assert.That(result, Is.EqualTo(Enumerable.Empty<int>()));
Assert.IsFalse(result.Any());
result.AssertSequenceEqual();
Assert.False(result.GetEnumerator().MoveNext());
Assert.That(result.GetEnumerator().MoveNext(), Is.False);
Assert.IsEmpty(result);
```
were replaced by:
```c#
Assert.That(result, Is.Empty);
```

Make empty sequence checks consistent in tests

---

MoreLinq.Test/CartesianTest.cs
MoreLinq.Test/ExcludeTest.cs
MoreLinq.Test/InterleaveTest.cs
MoreLinq.Test/LagTest.cs
MoreLinq.Test/LeadTest.cs
MoreLinq.Test/OrderByTest.cs
MoreLinq.Test/PermutationsTest.cs
MoreLinq.Test/RandomSubsetTest.cs
MoreLinq.Test/RandomTest.cs
MoreLinq.Test/RankTest.cs
MoreLinq.Test/RepeatTest.cs
MoreLinq.Test/RunLengthEncodeTest.cs
MoreLinq.Test/SegmentTest.cs
MoreLinq.Test/SkipLastTest.cs
MoreLinq.Test/SliceTest.cs
MoreLinq.Test/SortedMergeTest.cs
MoreLinq.Test/SubsetTest.cs
MoreLinq.Test/WindowedTest.cs

in many tests we compare sequences using.
```c#
Assert.IsTrue(result.SequenceEqual(expectations));
```
this PR replaces the above approach by the following, so we can get a more meaningful error
```c#
Assert.That(result, Is.EqualTo(expectations));
```

Make sequences equality comparison consistent in tests

---

appveyor.yml

CI build on AppVeyor is [broke](https://ci.appveyor.com/project/raboof/morelinq/build/941) with cd737c861d6d1fdfdaa1a211949a7adbd7d24ab3 due to the error:
```
[00:00:26] C:\Users\appveyor\AppData\Roaming\npm\node_modules\eclint\node_modules\gulp-reporter\node_modules\fs-extra\lib\fs\index.js:87
[00:00:26] exports.write = function (fd, buffer, ...args) {
[00:00:26]                                       ^^^
[00:00:26] 
[00:00:26] SyntaxError: Unexpected token ...
[00:00:26]     at exports.runInThisContext (vm.js:53:16)
[00:00:26]     at Module._compile (module.js:373:25)
[00:00:26]     at Object.Module._extensions..js (module.js:416:10)
[00:00:26]     at Module.load (module.js:343:32)
[00:00:26]     at Function.Module._load (module.js:300:12)
[00:00:26]     at Module.require …
```

Fix eclint-ing in CI build 🚧

---

MoreLinq.Test/CartesianTest.cs
MoreLinq/Cartesian.cs

This PR fixes for #488.
Initial push contains bd628dea2f844efb0089bb8a4504b6e341616204 that uses `TestingSequence` to demonstrate that the test break.

Change Cartesian to avoid re-iterating second sequence

---

.travis.yml
global.json

Seems that [`dotnet` muxer uses the latest patch within the same _hundreds_](https://github.com/johnbeisner/core-setup/blob/5d6e8afba2379bb698e50f2ebe0282b1f7c267ac/src/corehost/cli/fxr/fx_muxer.cpp#L694-L702
):
```cpp
if (global_cli_version.empty() ||
// If a global cli version is specified:
//   pick the greatest version that differs only in the 'minor-patch'
//   and is semantically greater than or equal to the global cli version specified.
(ver.get_major() == specified.get_major() && ver.get_minor() == specified.get_minor() &&
(ver.get_patch() / 100) == (specified.get_patch() / 100) && ver >= specified))
{
max_ver = std::max(ver, max_ver);
}
```

Upgrade to .NET Core SDK 2.1.200

---

MoreLinq.Test/RepeatTest.cs
MoreLinq/Repeat.cs

This PR addresses #489 and a long-standing to-do comment in the code.

Avoid multiple enumerations in Repeat through caching

---

MoreLinq/Experimental/Await.cs

This PR addresses #502.
Changes:
- A continuation is used to post task completions to the main loop so they can be reported and yielded while the source is still being iterated
- A semaphore is used to gate concurrency (when limited)
The source iteration loop has been refactored considerably. It is more complex since it uses asynchronous notification and requires synchronisation of shared state. Previously, the naïve approach was to loop through the entire source, launching tasks and then wait in another loop to post notifications as they complete. That unfortunately led to the behaviour documented in #502.

Fix AwaitCompletion to yield results during source iteration

---

MoreLinq.Test/MaxByTest.cs
MoreLinq.Test/MinByTest.cs
MoreLinq/MaxBy.cs
MoreLinq/MinBy.cs

This PR addresses #380.
It adds support for partial query of `MinBy` and `MaxBy` without introducing any new methods. “It just works” with natural methods of LINQ like `Take` and `First`. It does this by introducing a new `IExtremaEnumerable<>`, which is now returned by `MinBy` and `MaxBy`:
```c#
public interface IExtremaEnumerable<out T> : IEnumerable<T>
{
IEnumerable<T> Take(int count);
IEnumerable<T> TakeLast(int count);
}
```
By composing `MaxBy` or `MinBy` with `Take` or `TakeLast`, the internal iteration is optimised to only keep the requested count of elements in memory at any given time. What's more, if `count` is 1 for either then yet another optimised version ensures that only a single element is maintained (i.e. no cost of a collection type is incurred). There are also …

Add support for partial Min/MaxBy

---

MoreLinq/MoreLinq.csproj

For more information, see “[Introducing Source Code Link for NuGet packages](https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html)”.

Publish repository details in package

---

MoreLinq.Test/FillBackwardTest.cs
MoreLinq.Test/FillForwardTest.cs
MoreLinq.Test/FlattenTest.cs
MoreLinq.Test/MemoizeTest.cs
MoreLinq.Test/MoveTest.cs
MoreLinq.Test/PartitionTest.cs
MoreLinq.Test/RepeatTest.cs
MoreLinq.Test/SkipLastTest.cs
MoreLinq.Test/ToLookupTest.cs

since [thery are not equivalent](https://github.com/morelinq/MoreLINQ/pull/492#discussion_r226183306).

Replaced Is.EquivalentTo by Is.EqualTo on tests

---

MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq/MoreLinq.csproj

This supersedes #398. The motivation is to allow declaration of expression variables in queries.

Upgrade to C# 7.3

---

MoreLinq.Test/ToDataTableTest.cs
MoreLinq/ToDataTable.cs

This PR fixes the bug raised in issue #564.

Fix ToDataTable to skip write-only properties

---

.travis.yml
appveyor.yml
build.cmd
build.sh

`dotnet --info` can be noisy when doing local builds. This PR removes `dotnet --info` from build scripts and adds it to CI build configurations.

Skip `dotnet --info` except during CI builds

---

MoreLinq/Choose.cs
MoreLinq/Extensions.g.cs

`Choose`, which [shipped in 3.0](https://github.com/morelinq/MoreLINQ/releases/tag/v3.0.0), was implemented as a query comprehension that was a chained composition of `Select` &rarr; `Where` &rarr; `Select`. This PR expands and hand-rolls the implementation because it's very straightforward and probably won't require any maintenance. A hand-rolled implementation avoids lambda allocations, delegate and virtual invocation costs as well as having to name the tuple elements of the `chooser` result.

Expand Choose implementation

---

MoreLinq.Test/TestingSequence.cs
MoreLinq.Test/WatchableEnumerator.cs

In other words, `MoveNext` on an `IEnumerator<>` isn't called once it has returned `false`.

Test that sequences are not iterated past their end

---

MoreLinq/MoreLinq.csproj
MoreLinq/ToDataTable.cs

This reverts to using C# 7.3 instead of 8. It is not a complete undoing of PR #604. We maintain the update to .NET Core SDK 2.2.200 and corresponding changes to build scripts and CI configurations.
The main development line of the project can't benefit enough from C# 8 features at the moment that were mentioned as the main motivation for PR #604 so there is no point in imposing a preview on other contributors. It also prevents people from source-embedding some operators in projects.
While this reverts the C# version, most of the infrastructure is in place for any experimentation with C# 8 in a branch. All it requires changing the `LangVersion` element in the project file.

Revert to C# 7.3

---

MoreLinq.Test/MoveTest.cs
MoreLinq/Move.cs

this fix issue https://github.com/morelinq/MoreLINQ/issues/605

fix Move operartor returns empty on second iteration

---

MoreLinq/Extensions.g.cs
MoreLinq/MaxBy.cs
MoreLinq/MinBy.cs

These methods no longer throw an exception if the source is empty.

Remove InvalidOperationException for MinBy and MaxBy in documentation

---

.travis.yml

This PR removes package restoration on Travis CI as part of the installation step as it is redundant with `dotnet restore` in `build.sh`:
https://github.com/morelinq/MoreLINQ/blob/478218ace49794dc018dfe03d92fafae8ea77968/build.sh#L4

Remove redundant package restore on Travis CI

---

MoreLinq/Backsert.cs
MoreLinq/CountMethods.cs
MoreLinq/EndsWith.cs
MoreLinq/Exclude.cs
MoreLinq/FullJoin.cs
MoreLinq/GroupAdjacent.cs
MoreLinq/Insert.cs
MoreLinq/Lag.cs
MoreLinq/Lead.cs
MoreLinq/MaxBy.cs
MoreLinq/OrderedMerge.cs
MoreLinq/Pairwise.cs
MoreLinq/Permutations.cs
MoreLinq/PreScan.cs
MoreLinq/RunLengthEncode.cs
MoreLinq/Scan.cs
MoreLinq/Segment.cs
MoreLinq/SkipUntil.cs
MoreLinq/SortedMerge.cs
MoreLinq/StartsWith.cs
MoreLinq/Window.cs

This PR replaces [using statements](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement) with [declarations](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations) for the benefit of having less indented code. Most using statements in iterator blocks usually extend and scoped until the end of the block.

Replace using statement with declaration

---

MoreLinq.Test/BatchTest.cs
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/ReadOnlyCollection.cs
MoreLinq/Batch.cs

This PR came out of the discussion in #619 but _does not_ address #619. It adds optimisations to `Batch` for collections (and lists) and specifically when a collection can entirely fit in a single bucket. It avoids eagerly allocating to the size argument only to trim down later.
This is an optimisation of `Batch` and not a defined behaviour.
/cc @kcragin

Optimize Batch for collection fitting a single bucket

---

MoreLinq.Test/ReturnTest.cs
MoreLinq/MoreLinq.csproj
MoreLinq/Return.cs
README.md

Here's a first go at the Return method. #615

Return implementation

---

.travis.yml
MoreLinq.Test/MoreLinq.Test.csproj
test.cmd
test.sh

This PR addresses issue #674 that drops support for following .NET Core runtimes that have reached end of life/support:
- .NET Core 2.0 end of support was 2018-10-01
- .NET Core 1.1 end of support was 2019-06-27
- .NET Core 1.0 end of support was 2019-06-27

Drop targets for end-of-life .NET Core versions

---

MoreLinq.Test/SkipUntilTest.cs
MoreLinq/SkipUntil.cs

~Fix a part of #649~
Fork of #660 
SkipUntil called MoveNext after sequence end

Fix SkipUntil to not call MoveNext past end of sequence

---

MoreLinq.Test/BatchTest.cs
MoreLinq/Batch.cs

This PR is for fixing issue #741.

Fix Batch regression when source is an empty collection

---

MoreLinq.Test/AggregateTest.cs
MoreLinq.Test/ChooseTest.cs
MoreLinq/AssertCount.cs
MoreLinq/Backsert.cs
MoreLinq/CountDown.cs
MoreLinq/CountMethods.cs
MoreLinq/EndsWith.cs
MoreLinq/Experimental/Await.cs
MoreLinq/Experimental/TrySingle.cs
MoreLinq/FallbackIfEmpty.cs
MoreLinq/Flatten.cs
MoreLinq/PadStart.cs
MoreLinq/SkipLast.cs
MoreLinq/StartsWith.cs
MoreLinq/TakeLast.cs

This PR replaces all explicit (and now redundant) type mentions in patterns for sake of non-null testing (in addition to introducing a variable) with the _object_ or _empty property pattern_ `{}`.
From **Property patterns** section of the [**Do more with patterns in C# 8**](https://devblogs.microsoft.com/dotnet/do-more-with-patterns-in-c-8-0/) blog entry.
> One thing that remains true of all type patterns including property patterns, is that they require the value to be non-null. That opens the possibility of the “empty” property pattern {} being used as a compact “not-null” pattern.

Replace explicit type mentions with object pattern

---

MoreLinq.Test/InterleaveTest.cs
MoreLinq/Interleave.cs

Interleave: Do not call GetEnumerator eagerly

---

test.sh

This technically belongs with commit ed10deb35c8aa093f7ad20ba62f62584b66b2100.

Fix (bash) test script to test against .NET Core 3.1

---

.travis.yml
appveyor.yml

This addresses #681 by not publishing from `master` anymore but a `deploy` branch that can always be synchronized with a fast-forward merge of `master`.

Deploy package only on CI build of "deploy"

---

MoreLinq.Test/MaxByTest.cs
MoreLinq.Test/MinByTest.cs
MoreLinq/MaxBy.cs

This PR fixes the bug reported in #760.
Note that the tests added in 86f6f5807a2bb84ecd40b482c9b0bce3f9ea3147 were testing `First`, `FirstOrDefault`, `Last` and `LastOrDefault` members of `System.Linq.Enumerable` rather than those from MoreLINQ that extend `IExtremaEnumerable<>`. This PR fixes that too. In fact, the bug only surfaced after realising that 86f6f5807a2bb84ecd40b482c9b0bce3f9ea3147 wasn't testing the right implementation.

Fix bug in LastOrDefault for extrema sequence

---

MoreLinq/Extensions.g.cs
MoreLinq/MaxBy.cs
MoreLinq/MinBy.cs

Fix return value docs for MinBy/MaxBy

---

test.cmd

The Windows script was testing against the .NET Core 3.0 runtime instead of 3.1 whereas `MoreLinq.Test.csproj` doesn't list the former as a target. This PR fixes that.

Fix .NET Core version in test script

---

.travis.yml
MoreLinq/MoreLinq.csproj
MoreLinq/Permutations.cs
global.json

This PR makes the minimal changes needed to update the project to use .NET 5.0 SDK.

Update to .NET 5.0 SDK

---

test.cmd

This PR fixes `test.cmd` that was running same test configuration several times since the framework-specific flag was missing.

Fix duplicate test runs on Windows

---

MoreLinq/Extensions.g.cs
MoreLinq/Partition.cs

Replaced "staisfying" with "satisfying" in documentation for the `Partition` extension method.

Fix typo in Partition return value documentation

---

MoreLinq/Fold.g.tt
MoreLinq/MoreLinq.csproj
MoreLinq/tt.cmd
MoreLinq/tt.sh
build.cmd
build.sh

This PR integrates `dotnet t4` invocation directly into `MoreLinq.csproj` for the following benefits:
- Works with `dotnet build`
- Shell scripts like `tt.*` are not needed anymore
- Uses incremental building built-into MSBuild; `dotnet t4` is not invoked unless one of the `*.g.tt` files is touched

Integrate templated code generation into project file

---

MoreLinq/MoreLinq.csproj
build.cmd
build.sh

This is a follow-up PR from PR #776. It disables parallel builds for `MoreLinq.csproj` for overall simplicity with respect to observed corner cases. It does not seem to slow down building in a noticeable way, but goes a long way to simplify the T4 code generation integration into the project file by not requiring a separate and special mode of execution with `-p:BuildInParallel=false`.

Disable parallel building due to T4 for simplicity

---

.editorconfig
Directory.Build.props
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.sln
MoreLinq/MoreLinq.csproj
bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj

This PR (centrally) enables use of C# 9 across all projects of the solution.

Enable use of C# 9 across all projects

---

MoreLinq.Test/Async/AsyncEnumerable.cs
MoreLinq.Test/MoreLinq.Test.csproj
appveyor.yml

This PR adds masking of `System.Linq` extensions for async streams, just as we have [masking for extensions for sequences](https://github.com/morelinq/MoreLINQ/blob/4f05254095f9cdf390630c7f720b0eeba1d81bb1/MoreLinq.Test/Enumerable.cs).

Mask "System.Linq" for async streams

---

bld/ExtensionsGenerator/Program.cs

This PR removes the namespace and `Program` class from the extensions generator project (by using top-level statements) to reduce nesting of all members that were static anyway.

Simpler extensions generator with namespace & program class

---

appveyor.yml

Various shell sections in `appveyor.yml` used different line-folding. This PR makes them all consistent.

Use consistent line-folding in CI YAML shell sections

---

MoreLinq.Test/ScanByTest.cs
MoreLinq/Collections/Dictionary.cs

This PR fixes a bug introduced by PR #582 in our dictionary implementation that accepts `null` keys. The bug can be observed via `ScanBy`:
```c#
var nil = (object)null;
var source = new[] { "foo", null, "bar", null, "baz" };
var result = source.ScanBy(c => c, k => nil, (i, k, e) => nil);
foreach (var item in result)
Console.WriteLine(item);
```
It prints the following:
[foo, ]
[, ]
[bar, ]
before throwing an `ArgumentNullException`:
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
at MoreLinq.Collections.Dictionary`2.TryGetValue(TKey key, TValue& value) in C:\projects\morelinq\MoreLinq\Collections\Dictionary.cs:line 69
at …

Fix dictionary bug when null key has null value

---

MoreLinq/Experimental/TrySingle.cs

There was a to-do comment pending since PR #582 that questioned whether we could be more honest with the signatures of `TrySingle` regarding `T` being `null` when cardinality isn't one. Starting with C# 9, it looks like we can finally address this with [unconstrained type parameter annotations](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/unconstrained-type-parameter-annotations#-annotation):
> In C#8, `?` annotations could only be applied to type parameters that were explicitly constrained to value types or reference types. In C#9, `?` annotations can be applied to any type parameter, regardless of constraints.
This PR fixes the signatures to be more honest and removes the need for the use of the dammit (`!`) operator within the implementation …

Fix "TrySingle" signature with honest nullable annotations

---

MoreLinq/FallbackIfEmpty.cs

As part of reviewing nullable reference annotations (#803), this PR attempts to simplify usage of the `!` operator in the internals of `FallbackIfEmpty.cs`. No public APIs are affected.
The following line from the code prior to this PR will cause a compiler warning CS8619 (nullability of reference types in source type doesn't match target type):
```cs
return FallbackIfEmptyImpl(source, 1, fallback, default!, default!, default!, null);
```
Because potential null values are passed to `FallbackIfEmptyImpl`, the return value will be `IEnumerable<T?>`.
One solution would be to use another `!` at the end of the method call. However, the overuse of `!` doesn't feel very clean. Also, the signature of `FallbackIfEmptyImpl` doesn't seem to signal intent as clearly as making the fallback values …

Cleanup ! operator usage in FallbackIfEmpty

---

MoreLinq.Test/LagTest.cs
MoreLinq.Test/LeadTest.cs
MoreLinq/Extensions.g.cs
MoreLinq/Lag.cs
MoreLinq/Lead.cs
MoreLinq/MoreEnumerable.cs

This PR adds to #803. Where a `TSource` is defaulted for missing lead/lag value, the signature now clearly says `TSource?`.
Unfortunately, this requires a small projection hop (via `Select`) of an [_optuple_](https://github.com/atifaziz/Optuple).

Fix "Lag" & "Lead" signatures with more honest nullable annotations

---

MoreLinq/ReverseComparer.cs

This PR fixes the nullable annotation for the underlying comparer supplied to the `ReverseComparer` constructor. This class is not part of the public API, but the PR is part of the overall effort of correcting nullable annotations.

Fix "ReverseComparer" signature with more honest nullable annotations

---

MoreLinq.Test/GroupAdjacentTest.cs
MoreLinq/GroupAdjacent.cs

This PR fixes the issue reported in #809.

Fix "GroupAdjacent" null key handling bug

---

MoreLinq.Test/FullGroupJoinTest.cs
MoreLinq/Extensions.g.cs
MoreLinq/FullGroupJoin.cs

Adding to morelinq#803. This PR fixes nullable annotations for comparers that are allowed to be null as per the documentation comments.

Fix "FullGroupJoin" signature with more honest nullable annotations

---

MoreLinq.Test/BatchTest.cs
MoreLinq/Batch.cs

add test to ensure that if someone try to reuse the internal array in batch (break change) the unit test will not pass

Add test to ensure Batch does not reuse internal array

---

.config/dotnet-tools.json
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.sln
MoreLinq/Aggregate.g.tt
MoreLinq/Cartesian.g.tt
appveyor.yml
bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
build.cmd
build.sh
global.json
test.cmd
test.sh

This PR adds the .NET 6 as a target while dropping retired .NET (Core) versions:
- .NET Core 2.1 end-of-life was August 21, 2021
- .NET 5.0 end-of-life was May 10, 2022

Add .NET 6 target while dropping .NET 5 & Core 2.1

---

MoreLinq/Batch.cs

If count is more than 0, then bucket is not null. If count is zero, then bucket is null. So check for null condition is not necessary here

Removed unnecessary `null` check in `Batch` method

---

.gitignore
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/coverlet.runsettings
appveyor.yml
test.cmd
test.sh

This PR fixes code coverage by migrating from **coverlet.msbuild** to the new **coverlet.collector**.

Fix code coverage with new collector

---

MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq/MoreLinq.csproj

This PR updates referenced packages to their latest versions. The two exceptions are **System.Linq.Async** and **System.Reactive** in the test project since their latest versions do not support .NET Framework 4.5.1.

Update referenced packages to latest versions

---

MoreLinq/Extensions.g.cs
MoreLinq/Flatten.cs

This PR adds to #803. If fixes _parts_ of `Flatten` to be _null-oblivious_. Since [`IEnumerator.Current`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.current) is [null-oblivious](https://github.com/dotnet/runtime/blob/5a400c212afdf8e675c9a1d38442e6d2f19f7b74/src/libraries/System.Private.CoreLib/src/System/Collections/IEnumerator.cs#L25-L27), the right call here seems to be to mark the `object` parameter of `IEnumerable<>` and `Func<,>` to be null-oblivious too (rather than `object?`).

Fix `Flatten` signature parts to be null-oblivious

---

MoreLinq/Batch.cs
MoreLinq/Extensions.g.cs

One of the `Batch` overloads was missing the `<remarks>` tags in the doc comments. This PR adds them.

Add missing remarks tags on `Batch` overload

---

MoreLinq/Extensions.g.cs
MoreLinq/ToDictionary.cs

This PR adds to issue #803, but constraining the `TKey` type parameter of `ToDictionary` overloads to `notnull`.

Constrain key type param in `ToDictionary` to `notnull`

---

MoreLinq/CountBy.cs
MoreLinq/ScanBy.cs

`CountBy` and `ScanBy` have a [look-up optimisation](https://github.com/morelinq/MoreLINQ/pull/207#issuecomment-258132466) (premature in hindsight?) that don't seem to be better/faster than a simpler version without any look-up optimisation, as demonstrated by the [benchmarks for `CountBy`](https://github.com/morelinq/MoreLINQ/files/9873267/benchmark.zip) below. In all instances, the unoptimised versions are faster for ordered _and_ unordered sequence inputs. This PR therefore removes the optimisations.
|                            Method |            Runtime |      Mean |    Error |    StdDev |    Gen0 |   Gen1 | Allocated |
|---------------------------------- |------------------- |----------:|---------:|----------:|--------:|-------:|----------:|
|               `CountBySortedNums` | …

Remove look-up optimizations in `CountBy`/`ScanBy`

---

MoreLinq/MoreLinq.csproj

This PR replaces the [**Nullable**](https://www.nuget.org/packages/Nullable) package with [**PolySharp**](https://www.nuget.org/packages/PolySharp/). It also allows removing the suppression of warning [NU5118](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5118).

Replace Nullable with PolySharp

---

MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/coverlet.runsettings

This PR updates to the latest version of [**coverlet.collector**](https://www.nuget.org/packages/coverlet.collector), which seems to restore coverage reporting.
Before this PR, run:
git checkout ac88c7ffdb943c88595bd47d36cf2b07ea941ae6
test.cmd
The coverage report at the end says no assemblies were covered:
Summary
Generated on: 30/10/2022 - 22:30:30
Parser: MultiReportParser (4x OpenCoverParser)
Assemblies: 0
Classes: 0
Files: 0
Line coverage:
Covered lines: 0
Uncovered lines: 0
Coverable lines: 0
Total lines: 0
No assemblies have been covered.
After applying this PR, the report instead reads:
Summary
Generated on: 30/10/2022 - 22:44:27
Parser: MultiReportParser (4x OpenCoverParser)
Assemblies: 1
Classes: 15
Files: 108
Line coverage: 93.1%
Covered lines: 3216
Uncovered lines: 237 …

Fix code coverage using latest coverlet collector

---

MoreLinq.Test/CountByTest.cs
MoreLinq.Test/ToDataTableTest.cs
MoreLinq/Collections/Dictionary.cs
MoreLinq/Experimental/Await.cs
MoreLinq/Extensions.g.cs
MoreLinq/MoreLinq.csproj
MoreLinq/PartialSort.cs
MoreLinq/Rank.cs
MoreLinq/ReverseComparer.cs
MoreLinq/ToDataTable.cs
MoreLinq/Trace.cs

This PR adds the .NET 6 target for the main library projects and adjusts mostly for nullability errors.

Adjust library for .NET 6 target

---

MoreLinq.Test/AggregateRightTest.cs
MoreLinq.Test/ScanRightTest.cs
MoreLinq/AggregateRight.cs
MoreLinq/Extensions.g.cs
MoreLinq/ScanRight.cs

This PR replaces most `string.Format` invocations with string interpolation.

Use string interpolation

---

MoreLinq.Test/AggregateRightTest.cs
MoreLinq.Test/BreakingAction.cs
MoreLinq.Test/BreakingFunc.cs
MoreLinq.Test/ConsumeTest.cs
MoreLinq.Test/GroupAdjacentTest.cs
MoreLinq.Test/LagTest.cs
MoreLinq.Test/LeadTest.cs
MoreLinq.Test/ScanByTest.cs
MoreLinq.Test/ScanRightTest.cs
MoreLinq.Test/SegmentTest.cs
MoreLinq.Test/TraverseTest.cs
MoreLinq/Consume.cs
MoreLinq/EquiZip.cs
MoreLinq/IndexBy.cs
MoreLinq/NestedLoops.cs
MoreLinq/Partition.cs
MoreLinq/Scan.cs
MoreLinq/Segment.cs
MoreLinq/TakeEvery.cs
MoreLinq/ZipLongest.cs
MoreLinq/ZipShortest.cs

This PR discards unused parameters in lambda expressions.

Discard unused parameters

---

MoreLinq.Test/FlattenTest.cs
MoreLinq.Test/FromTest.cs
MoreLinq.Test/FullGroupJoinTest.cs
MoreLinq.Test/NullArgumentTest.cs
MoreLinq.Test/TestExtensions.cs
MoreLinq/Backsert.cs
MoreLinq/Exclude.cs
MoreLinq/Fold.cs
MoreLinq/MaxBy.cs
MoreLinq/OrderedMerge.cs

This PR refactors switch statements into expressions.

Rewrite switch statements as expressions

---

MoreLinq.Test/TraceTest.cs
MoreLinq/MoreEnumerable.cs

This PR converts using statements to declarations for simplicity.

Convert using statements to declarations

---

MoreLinq.Test/AggregateTest.cs
MoreLinq.Test/FlattenTest.cs
MoreLinq.Test/LeadTest.cs
MoreLinq.Test/MemoizeTest.cs
MoreLinq.Test/RandomTest.cs
MoreLinq.Test/TraceTest.cs
MoreLinq/Experimental/Await.cs
MoreLinq/FallbackIfEmpty.cs
MoreLinq/Flatten.cs
MoreLinq/Partition.cs
MoreLinq/Split.cs
MoreLinq/Subsets.cs
MoreLinq/ToDataTable.cs
bld/ExtensionsGenerator/Program.cs

This PR revises some expressions to take advantage of pattern matching.

Revise & take advantage of pattern matching

---

MoreLinq/RandomSubset.cs

This PR rewrites a swap more succinctly using tuple assignment.

Rewrite swap more succinctly (via tuples)

---

MoreLinq/MoreLinq.csproj

This removes PolySharp as package dependency from the published nuget package of MoreLINQ.

Make PolySharp a build-time dependency

---

test.cmd
test.sh

This PR fixes test scripts to also execute unit tests on the .NET 7 runtime. It's a follow-up fix to PR #871.

Fix test scripts to test on .NET 7 runtime

---

MoreLinq.Test/MaxByTest.cs
MoreLinq.Test/MinByTest.cs
MoreLinq/Extensions.g.cs
MoreLinq/MaxBy.cs

This PR replaces `MayBeNull` annotations with `?` in `IExtremaEnumerable<>` members.

Replace `MayBeNull` with `?` in `IExtremaEnumerable` members

---

MoreLinq.Test/FlattenTest.cs
MoreLinq.Test/MoreLinq.Test.csproj

This PR enables the nullable context in the unit tests for `Flatten`.
This is a follow-up to PR #847 that adds to #803.

Enable nullable context in `Flatten` tests

---

.config/dotnet-tools.json

This PR updates the [ReportGenerator tool](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool) to version [5.1.11](https://github.com/danielpalme/ReportGenerator/releases/tag/v5.1.11).

Update ReportGenerator tool to 5.1.11

---

bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
bld/ExtensionsGenerator/Program.cs

This PR enables the nullable context for the extensions generator project and addresses resulting null-safety issues.

Enable nullable context for extensions generator

---

MoreLinq/Lookup.cs

This PR updates the implementations of [`Lookup`](https://github.com/dotnet/runtime/blob/v7.0.0/src/libraries/System.Linq/src/System/Linq/Lookup.cs) and [`Grouping`](https://github.com/dotnet/runtime/blob/v7.0.0/src/libraries/System.Linq/src/System/Linq/Grouping.cs#L48-L141) from .NET 7 sources. It allows the code to participate to be subjected to nullability checks from .NET 6 onwards.

Sync `Lookup` + `Grouping` from .NET 7 sources

---

MoreLinq.Test/PartialSortByTest.cs
MoreLinq.Test/PartialSortTest.cs

This PR is for #803. There are no nullability changes required for `.PartialSort()`

PartialSort: #nullable enable on tests

---

MoreLinq/Reactive/Subject.cs

This PR fixes the nullability annotation in the private helper method of `Subject` so a null-forgiving operator is not needed at the call site.

Fix nullability annotation in `Subject`

---

MoreLinq.Test/FallbackIfEmptyTest.cs
MoreLinq/Assume.cs
MoreLinq/Debug.cs
MoreLinq/Experimental/Await.cs
MoreLinq/Experimental/Memoize.cs
MoreLinq/FallbackIfEmpty.cs
MoreLinq/Fold.cs
MoreLinq/Lookup.cs
MoreLinq/Pad.cs
MoreLinq/PartialSort.cs
MoreLinq/Partition.cs
MoreLinq/Reactive/Subject.cs

This PR introduces `Debug.Assert` that's defined similarly to [`System.Diagnostics.Debug.Assert`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert?view=net-7.0#system-diagnostics-debug-assert(system-boolean-system-string)) to help eliminate the bulk uses of the null-forgiving operator (`!`). The assertion more explicitly states the illegal case, and if triggered, will also relay the offending condition in the message. It also eliminates needing to suppress [CS8602](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-dereference-of-null) and [CS8603](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference) …

Replace null-forgiving operator uses with debug assertions

---

MoreLinq/Partition.cs

This introduces a null-check in order to fail-fast on a `null` `resultSelector` value.

Add null check for `Partition`

---

MoreLinq/Experimental/Memoize.cs

~This PR is for https://github.com/morelinq/MoreLINQ/issues/803.~ It updates to use the new switch expression for the operator.

Rewrite switch in `Memoize` as expression

---

MoreLinq.Test/PartitionTest.cs
MoreLinq/Partition.cs

This PR adds to https://github.com/morelinq/MoreLINQ/issues/803. It uses nullable `TKey` values in the implementation to more accurately express the code.

Cleanup `Partition` Nullability

---

MoreLinq/Batch.cs
MoreLinq/GroupAdjacent.cs
MoreLinq/IdFn.cs
MoreLinq/Identity.cs
MoreLinq/OrderedMerge.cs
MoreLinq/Rank.cs
MoreLinq/Split.cs

Currently, the C# compiler does not de-dupe methods, including identity methods, such as `x => x`. This means each instance of `x => x` is compiled as a separate method; and each method must be JIT to asm separately, and must be done so for each type separately.
Adding an `Identity` method improves JIT significantly:
* Fewer methods to JIT
* Since these methods are generic, they have to be JITted separately for each type; Identity<T> can share the JITted versions across multiple call sites
Until .net7.0 + tiered PGO, these methods will not get inlined because they are accessed via delegate. This means they also take additional space in memory due to the translated code.

Add identity method to reduce JIT-ing

---

MoreLinq.Test/EquiZipTest.cs
MoreLinq.Test/ZipShortestTest.cs

This PR enables nullable context for tests for remaining `*Zip*` methods, namely `EquiZip` and `ZipShortest`. It adds to #803.
This was forked from unrelated changes in PR #900.

Enable nullable context for remaining `*Zip*` tests

---

MoreLinq.Test/AssertCountTest.cs
MoreLinq.Test/AssertTest.cs
MoreLinq.Test/CartesianTest.cs
MoreLinq.Test/CompareCountTest.cs
MoreLinq.Test/ConsumeTest.cs
MoreLinq.Test/FallbackIfEmptyTest.cs
MoreLinq.Test/FullGroupJoinTest.cs
MoreLinq.Test/GroupAdjacentTest.cs
MoreLinq.Test/LagTest.cs
MoreLinq.Test/LeadTest.cs
MoreLinq.Test/MaxByTest.cs
MoreLinq.Test/MinByTest.cs
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/PermutationsTest.cs
MoreLinq.Test/RandomSubsetTest.cs
MoreLinq.Test/RandomTest.cs
MoreLinq.Test/RankTest.cs
MoreLinq.Test/ScanTest.cs
MoreLinq.Test/SegmentTest.cs
MoreLinq.Test/SequenceTest.cs
MoreLinq.Test/SliceTest.cs
MoreLinq.Test/SubsetTest.cs
MoreLinq.Test/ToDataTableTest.cs
MoreLinq.Test/TransposeTest.cs
MoreLinq.Test/WindowTest.cs

This PR addresses #909. It adds the **NUnit.Analyzers** package to the tests project and addresses the following warnings/errors:
- [NUnit2015]: Consider using `Assert.That(actual, Is.SameAs(expected))` instead of `Assert.AreSame(expected, actual)`
- [NUnit2005]: Consider using `Assert.That(actual, Is.EqualTo(expected))` instead of `Assert.AreEqual(expected, actual)`
- [NUnit2031]: Consider using `Assert.That(actual, Is.Not.SameAs(expected))` instead of `Assert.AreNotSame(expected, actual)`
[NUnit2015]: https://github.com/nunit/nunit.analyzers/blob/3.5.0/documentation/NUnit2015.md
[NUnit2005]: https://github.com/nunit/nunit.analyzers/blob/3.5.0/documentation/NUnit2005.md
[NUnit2031]: https://github.com/nunit/nunit.analyzers/blob/3.5.0/documentation/NUnit2031.md

Add NUnit.Analyzers, addressing warnings

---

MoreLinq.Test/RankTest.cs
MoreLinq/Extensions.g.cs
MoreLinq/Rank.cs

This PR adds to #803. It fixes the nullability of `comparer` argument of one of `Rank` overloads.

Fix nullability of `Rank` comparer argument

---

MoreLinq.Test/ToDataTableTest.cs
MoreLinq/Extensions.ToDataTable.g.cs
MoreLinq/ToDataTable.cs

This fixes the nullability of `ToDataTable` expressions argument, adding to #803. The actual and possibly boxed return type of each expression (`object`) is not really used; the actual type of the accessed property is. As a result, there is no requirement that the property type not be nullable and in fact can be limiting. This PR allows expressions to return `object?`.
Suppose the following record:
```c#
sealed record Person
{
public required string FirstName { get; init; }
public string? MiddleName { get; init; }
public required string LastName { get; init; }
}
```
Before this PR, the following will issue a nullability warning ([CS8603](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference)) …

Fix nullability of `ToDataTable` expressions argument

---

MoreLinq/Permutations.cs
MoreLinq/Subsets.cs

This PR seals two private enumerators implementations since neither is designed for subclassing.

Seal private enumerators

---

MoreLinq/Permutations.cs

This PR follows-up on a miss in PR #890.

Replace `!` with debug assertion in `Permutations`

---

MoreLinq.Test/LeadTest.cs
MoreLinq.Test/PartialSortByTest.cs
MoreLinq.Test/PartialSortTest.cs
MoreLinq.Test/PermutationsTest.cs
MoreLinq.Test/RankTest.cs
MoreLinq/CountDown.cs
MoreLinq/CountMethods.cs
MoreLinq/Experimental/Await.cs
MoreLinq/Experimental/Memoize.cs
MoreLinq/Extensions.g.cs
MoreLinq/FillBackward.cs
MoreLinq/FillForward.cs
MoreLinq/FullJoin.cs
MoreLinq/LeftJoin.cs
MoreLinq/Permutations.cs
MoreLinq/Random.cs
MoreLinq/RandomSubset.cs
MoreLinq/RightJoin.cs
MoreLinq/ScanRight.cs
MoreLinq/Subsets.cs
MoreLinq/Window.cs

This PR fixes typos across (doc) comments.

Fix typos in comments

---

MoreLinq.Test/MemoizeTest.cs
MoreLinq.Test/TraceTest.cs
MoreLinq/ToDataTable.cs

This PR marks local functions as `static`, those that don't access variables from their enclosing scope.

Mark local function static where possible

---

MoreLinq.Test/MemoizeTest.cs
MoreLinq.Test/TestingSequence.cs

This PR addresses a to-do comment by removing `DisposalTrackingSequence` in `MemoizeTest` and using `TestingSequence` instead. This required enhancing `TestingSequence` with an option to allow re-iteration of a sequence as well as exposing a property to assert if the enumerator was disposed.

Address to-do about consolidating testing sequence implementations

---

MoreLinq/Permutations.cs

This PR refactors swaps in `Permutations` to use tuples, which reads simpler and more succinct.

Use tuples to perform swap in `Permutations`

---

MoreLinq.Test/BatchTest.cs
MoreLinq/Experimental/Batch.cs

This PR fixes the `ICurrentBuffer<>` indexer implementation, used in `Batch`, to throw `IndexOutOfRangeException` instead of `ArgumentOutOfRangeException`. This is to respect the contract of `IList<T>[index]`, which should [throw `ArgumentOutOfRangeException` for an index index](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ilist-1.item?view=net-7.0#exceptions).
This is a follow-up to [a review comment](https://github.com/morelinq/MoreLINQ/pull/924#discussion_r1070624671) by @viceroypenguin on PR #924.

Fix exception thrown by current buffer index implementation

---

MoreLinq/Permutations.cs

This PR refactors a while-loop into a simpler for-loop (with two loop variables) in the `NextPermutation` implementation of `Permutations` operator.

Rewrite next permutation while-loop into a for-loop

---

MoreLinq.Test/AssertCountTest.cs
MoreLinq.Test/FoldTest.cs
MoreLinq/AssertCount.cs
MoreLinq/Fold.cs

The formatting of the error message was duplicated between `AssertCount` and `Fold`. This PR consolidates that duplication by using a common formatting method.

Consolidate error formatting between `AssertCount` and `Fold`

---

MoreLinq.Test/MoreLinq.Test.csproj

This PR removes [disabling of default compile items](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enabledefaultcompileitems), which was probably a dated hack from #261, to simplify the project file.
---
PS Credit to @viceroypenguin for [pointing this out](https://github.com/morelinq/MoreLINQ/pull/924/files#r1070623101).

Enable default compile items in test project

---

MoreLinq.Test/TagFirstLastTest.cs

Add 
- TagFirstLastEvaluatesSourceLazily ensure that TagFirstLast doesn't evaluate the whole source uselessly.
- TagFirstLastWithSourceSequenceOfZero for 100% code coverage in #643

Additional tests for `TagFirstLast`

---

MoreLinq.Test/ToArrayByIndexTest.cs
MoreLinq/ToArrayByIndex.cs

This PR fixes the bug identified in issue #931.

Fix off-by-one index validation bug in `ToArrayByIndex`

---

MoreLinq.Test/TagFirstLastTest.cs
MoreLinq/TagFirstLast.cs

This implementation avoid the creation of a `KeyValuePair` for each item of the sequence.
It improves evaluation of a 0 returning resultSelector by a factor of 3

Decompose `TagFirstLast` implementation for speed

---

MoreLinq.Test/CurrentThreadCultureScope.cs
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq/Experimental/Await.cs
MoreLinq/MoreLinq.csproj
test.cmd
test.sh

This PR closes #933.
Support for .NET Framework is retargeted from 4.5.1 that's no longer supported to the minimum supported version 4.6.1.

Updated .NET Framework target to 4.6.2

---

MoreLinq.Test/KeyValuePair.cs
MoreLinq.Test/ReturnTest.cs
MoreLinq.Test/SampleData.cs
MoreLinq.Test/ShuffleTest.cs
MoreLinq.Test/ToDataTableTest.cs
MoreLinq.Test/TraverseTest.cs
MoreLinq.Test/WatchableEnumerator.cs
MoreLinq/Experimental/Await.cs
MoreLinq/GroupAdjacent.cs
MoreLinq/Return.cs

This PR uses target-typed new expressions to avoid repeating the type in `new` expressions where it's very obvious.

Remove redundant type spec on obvious new expressions

---

.editorconfig
MoreLinq/Lookup.cs

This PR sets the project's modifier preference to omit if default and enforces it through a warning.

Declare & set modifier preference (IDE0040) severity

---

appveyor.yml

The CI config prepends `~/.dotnet` to `PATH` for builds on Ubuntu. [`~` works for Bash, but not much else](https://stackoverflow.com/a/58150161/6682) so this PR updates the config to use `$HOME/.dotnet`.

Fix home when setting path during CI build

---

MoreLinq/MoreLinq.csproj
MoreLinq/tt.cmd
MoreLinq/tt.sh
build.cmd
build.sh

This reverts commit f669558facbbec9269a466c81594d5db8a19b4d1 from merge of PR #776.
The integration required parallel builds to be turned off for **MoreLinq**. Since PR #776, more frameworks are being targeted and this slows the build down considerably, taking per target 5 seconds (on my machine) and a total time of approximately 44 seconds:
13:15:15:755	Rebuild started...
13:15:16:123	Restored A:\MoreLINQ\main\bld\ExtensionsGenerator\MoreLinq.ExtensionsGenerator.csproj (in 38 ms).
13:15:16:123	Restored A:\MoreLINQ\main\MoreLinq\MoreLinq.csproj (in 127 ms).
13:15:16:372	1>------ Rebuild All started: Project: MoreLinq.ExtensionsGenerator, Configuration: Debug Any CPU ------
13:15:16:374	2>------ Rebuild All started: Project: MoreLinq, Configuration: Debug Any CPU ------
13:15:16:383 …

Revert integration of T4 code generation into project file

---

MoreLinq/CountDown.cs

`CountDown` has a path optimised for when the `source` parameter is a list, but it was poorly written respect to performance. It accessed the list `Count` property 3 times, twice during each iteration of the loop. Each access is a virtual dispatch so it seems to adds up, making it perform _worse_ than when the source is a sequence (zero net optimisation). This PR fixes that by accessing `Count` once, storing it in a local and then using the local throughout. This improves the performance by 40%.
|            Method |               Source |     Mean |    Error |   StdDev |   Median | Allocated |
|------------------ |--------------------- |---------:|---------:|---------:|---------:|----------:|
| MoreLinqCountDown |       Int32[1000000] | 21.31 ms | 0.426 ms | 1.209 ms | 21.02 ms |     119 …

Improve list optimisation in `CountDown`

---

MoreLinq.Test/AssertCountTest.cs
MoreLinq.Test/CountDownTest.cs
MoreLinq.Test/FallbackIfEmptyTest.cs
MoreLinq.Test/PadStartTest.cs
MoreLinq.Test/SkipLastTest.cs
MoreLinq.Test/TakeLastTest.cs
MoreLinq/AssertCount.cs
MoreLinq/CollectionLike.cs
MoreLinq/CountDown.cs
MoreLinq/CountMethods.cs
MoreLinq/EndsWith.cs
MoreLinq/Experimental/TrySingle.cs
MoreLinq/FallbackIfEmpty.cs
MoreLinq/MoreEnumerable.cs
MoreLinq/PadStart.cs
MoreLinq/SkipLast.cs
MoreLinq/StartsWith.cs
MoreLinq/TakeLast.cs

This PR fixes #943.
It fixes the optimised path in the following operators for when the source is a collection:
- `AssertCount`
- `CountDown`
- `FallbackIfEmpty`
- `PadStart`
- `SkipLast`
- `TakeLast`
All of the above operators have deferred execution semantics, but they were binding to the source collection count when invoked and not when the resulting sequence was iterated. Consequently, if the source collection was updated before iteration, the (cached) count and the resulting sequence would be incorrect.
Tests have been added to avoid regressions in the future.
Some tests were removed because the optimisations they were exercising couldn't be maintained anymore. For example, if `AssertCount` could determine that the source was a collection and had the right count, then it would return …

Fix collection-optimized paths to be at iteration-time

---

MoreLinq/CollectionLike.cs
MoreLinq/ListLike.cs

This PR addresses the [feedback](https://github.com/morelinq/MoreLINQ/pull/472#discussion_r1085222239) from @fsateler on PR #472:
> `rx` means `read-execute` in the unix model. Perhaps `_ro` for `read-only` might be better?

Rename read-only list/collection field of `ListLike`/`CollectionLike`

---

MoreLinq.Test/MemoizeTest.cs
MoreLinq.Test/TestingSequence.cs
MoreLinq.Test/WatchableEnumerator.cs

This PR updates the assertions made in `TestingSequence`:
* Per the [specification](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose), it is not a failure to call `.Dispose()` multiple times. The `.Dispose()` method is expected to be idempotent, such that it is callable multiple times without throwing an exception. Updated to allow relying on this specification via `Options.AllowRepeatedDispoals`.
* Per the [specification](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.movenext?view=net-7.0#remarks), it is not a failure to call `.MoveNext()` after receiving a `false` response. The enumerator is simply expected to continue to return `false` for each following call. As such, we should not be afraid to take advantage of …

Improve and Validate `TestingSequence` assertions

---

MoreLinq/CollectionLike.cs
MoreLinq/ListLike.cs
MoreLinq/MoreEnumerable.cs

This PR consolidate structural differences between `CollectionLike<T>` and `ListLike<T>`:
- The `TryAsCollectionLike` as extension is moved to `CollectionLike`.
- Type construction helpers for `ListLike<T>` are in-lined due to single use.

Consolidate structural differences in `*Like` types

---

MoreLinq/MoreLinq.csproj

Since `dotnet t4` is no longer invoked during a build via the project file (since #940), the disabling of parallel builds that was done as a specific workaround for T4 no longer applies and therefore this PR removes that disabling. It should have been done as part of PR #940.

Revoke (obsolete) disabling of parallel builds

---

MoreLinq/MoreLinq.csproj
MoreLinq/tt.cmd
MoreLinq/tt.sh
appveyor.yml

This PR restores some of PR #776 to re-integrate `dotnet t4` invocation from the project, but taking advantage of conditional execution of targets only if the outputs are out-of-date with respect to inputs.
During the CI builds, the templates are _touched_ to update their timestamps and force execution of the templates to later validate that generated code is fresh.

Run T4 templates if targets are out-of-date

---

MoreLinq.Test/NullArgumentTest.cs

This PR discards an unused expression value that should (and eventually would) have been triggered by [IDE0058](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0058).

Discard unused expression value (IDE0058)

---

MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/NullArgumentTest.cs
appveyor.yml
test.cmd
test.sh

This PR removes testing on [.NET Core 3.1](https://dotnet.microsoft.com/en-us/download/dotnet/3.1) that's no longer supported since last month (December 13, 2022).

Remove testing on .NET Core 3.1 that's no longer supported

---

MoreLinq/Extensions.g.cs
MoreLinq/Interleave.cs
MoreLinq/Lag.cs
MoreLinq/Lead.cs
MoreLinq/Permutations.cs
MoreLinq/Slice.cs
MoreLinq/SortedMerge.cs
MoreLinq/Subsets.cs
MoreLinq/Window.cs

The PR fixes the following issues:
- formatting (use `<para>` instead of `<br/>`, missing `<c>` and `<see>`)
- inconsistencies (`<remarks/>` at the end instead of after `<summary>`)
- grammar (missing period/full-stop at the end of most sentences)
- wrapping
- code examples
that appeared consistently in the doc comments of the following operators:
- `Interleave`
- `Lag`
- `Lead`
- `Permutations`
- `Slice`
- `SortedMerge`
- `Subsets`
- `Window`

Fix some doc comments

---

MoreLinq/Debug.cs

I assume the argument expression in `message` was originally meant to be used.

Make use of `message` in `Debug.Assert`

---

MoreLinq/ToDelimitedString.g.cs
MoreLinq/ToDelimitedString.g.tt

This PR removes all `StringBuilderAppenders` members that were designed to serve as static caches of delegates for use in `ToDelimitedString` implementations. This may have been significant in the past, but now using a simple static lambda seems to be simpler _and_ the compiler-generated cached delegate run faster. It does however come at the cost of an additional allocation because while the lambdas themselves are static, the delegate caching gets hosted into a non-static class (`<>c` below) generated by the C# compiler and the bodies converted into _regular instance-based_ methods:
```c#
[Serializable]
[CompilerGenerated]
private sealed class <>c
{
[System.Runtime.CompilerServices.Nullable(0)]
public static readonly <>c <>9 = new <>c();
// ...omitted for brevity...
public static …
```

Use compiler-generated delegate caches in `ToDelimitedString`

---

MoreLinq/ToDataTable.cs
global.json

This PR updates `global.json` to require .NET SDK 7.0.200,

Update .NET SDK to 7.0.200

---

MoreLinq.Test/BatchTest.cs
MoreLinq.Test/TestExtensions.cs
MoreLinq/Batch.cs

The `Batch` operator contains similar problems to those addressed in issue #943/PR #946. This PR removes all collection optimizations, since they are all based on caching the collection count at initial call instead of run-time.

Fix collection-optimized paths for `Batch`

---

MoreLinq/Fold.cs
MoreLinq/Fold.g.cs
MoreLinq/Fold.g.tt

This PR simplifies the implementation of `Fold`. The existing `FoldImpl` is unnecessary and onerous to maintain. Since it receives 18 arguments, it must check which one should be non-`null` and then it must select that one for `Fold`ing. This a) creates additional branches and code bloat, and b) adds an additional method that must be maintained. 
It is better to have each overload of `Fold` do what it needs to do directly. This avoids branching and the `Assume.NotNull()` check, and simplifies the code significantly.

Simplify `Fold` Implementation

---

MoreLinq/Extensions.g.cs
MoreLinq/Fold.g.cs
MoreLinq/Fold.g.tt

This PR fixes minor inconsistencies in doc comments of `Fold` overloads.

Fix inconsistencies in `Fold` doc

---

MoreLinq/AssertCount.cs
MoreLinq/Extensions.g.cs
MoreLinq/Fold.cs

This PR implements `Fold` entirely in its own terms; that is, without any dependency on or composing on top of `AsserCount` and `Index`. `Fold` is expected to be used for short sequences (up to a maximum length of 16 elements), so this has the positive effect of avoiding extra enumerator allocations and virtual dispatches.

Implement `Fold` entirely in its own terms

---

MoreLinq/ToDelimitedString.g.cs
MoreLinq/ToDelimitedString.g.tt

This PR removes no longer used imports in `ToDelimitedString`.

Remove unused imports (in `ToDelimitedString`)

---

MoreLinq/AssertCount.cs
MoreLinq/Extensions.g.cs

Just the way it was done for `ToDelimitedString` in PR #966, this PR does the same for `AssertCount`.

Use compiler-generated delegate cache in `AssertCount`

---

MoreLinq/Aggregate.g.cs
MoreLinq/Aggregate.g.tt
MoreLinq/Cartesian.g.cs
MoreLinq/Cartesian.g.tt
MoreLinq/Fold.g.cs
MoreLinq/Fold.g.tt
MoreLinq/ToDelimitedString.g.cs
MoreLinq/ToDelimitedString.g.tt

This PR fixes #981 by enabling nullable context for the following extensions:
- `ToDelimitedString`
- `Aggregate`
- `Fold`
- `Cartesian`

Enable nullable context for extensions generated via T4

---

MoreLinq/Extensions.g.cs
MoreLinq/NestedLoops.cs
MoreLinq/Permutations.cs

This PR fixes #978, by using `ulong` internally instead of `int` and adding checked arithmetic. This limits to 18,446,744,073,709,551,615 permutations and will overflow thereafter. A document comment has also been added to call out this limitation.
Due to the computationally expensive nature of enumerating permutations of a source with more than 12 elements, no unit test has been added to exercise the fix. However, the [following LINQPad query](http://share.linqpad.net/73ibc7.linq) was used as an eyeball test: [`MoreLinqPermutations.zip`](https://github.com/morelinq/MoreLINQ/files/10876399/MoreLinqPermutations.zip). At the time of opening this PR, it will use [latest NuGet package version (3.4.0)](https://www.nuget.org/packages/morelinq/3.4.0) and will exercise the bug. If the package …

Fix `Permutations` for when source length is >12

---

build.cmd
builddocs.cmd
msbuild.cmd
pack.cmd
test.cmd

This PR fixes error handling in Windows batch script and removes use of some quirks (e.g. `goto :EOF` and `popd` do not reset the `ERRORLEVEL` on success) to ensure more robust propagation of errors/failures.

Fix error handling in Windows batch scripts

---

appveyor.yml
test.cmd
test.sh

This PR fixes #95 by skipping the build step in `test.cmd` and `test.sh` when an environment variable named `SKIP_TEST_BUILD` is defined and its value is anything but `false`. During a CI build `SKIP_TEST_BUILD` is set to `true`.

Skip build when testing on CI

---

MoreLinq.Test/UnfoldTest.cs
MoreLinq/Unfold.cs

Fix `Unfold` bug so iterations are repeatable

---

bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
bld/ExtensionsGenerator/Program.cs

This PR uses [docopt.net](https://www.nuget.org/packages/docopt.net) to replace/reduce CLI argument handling code in the extensions generator program.

Use docopt.net to parse extensions generator CLI args

---

MoreLinq.Test/FillForwardTest.cs
MoreLinq/FillForward.cs

Fix bug in `FillForward` when filler is `null`

---

MoreLinq/ToDataTable.cs

This is a refactoring PR that improves `ToDataTable`.
The internal `BuildOrBindSchema` method created a schema projection (`schemas`), but the two paths taken by the code (based on whether the table had columns) accessed distinct parts of the projection. This PR removes the query to save on allocation costs, moves the only shared bit into a new local function called `GetElementaryTypeOfPropertyOrField` and the rest is dissolved into each code path.

Dissolve schema query into distinct `ToDataTable` paths

---

MoreLinq/ToDataTable.cs

This PR fixes the nullable annotations on signatures of internal methods that make up the `ToDataTable` implementation, such as `BuildOrBindSchema` and `CreateShredder`.

Fix schema binding signature in `ToDataTable` implementation

---

MoreLinq.Test/AggregateTest.cs
MoreLinq.Test/AppendTest.cs
MoreLinq.Test/DistinctByTest.cs
MoreLinq.Test/Enumerable.cs
MoreLinq.Test/GroupAdjacentTest.cs
MoreLinq.Test/PartialSortTest.cs
MoreLinq.Test/PrependTest.cs
MoreLinq.Test/SkipLastTest.cs
MoreLinq.Test/TakeLastTest.cs

This PR re-enables tests for extensions hidden in PR #945. This not only helps recover the coverage (from 90.7% to 93.3%), requires less maintenance of conditionally compiled code, but also exercises those extensions that are still accessible via `MoreLinq.Extensions.*Extension` wrappers.
Coverage before:
Summary
Parser: MultiReport (4x OpenCover)
Assemblies: 1
Classes: 20
Files: 113
Line coverage: 90.7%
Covered lines: 3104
Uncovered lines: 318
Coverable lines: 3422
Total lines: 15386
Branch coverage: 87.4% (2097 of 2399)
Covered branches: 2097
Total branches: 2399
Method coverage: 91.6% (482 of 526)
Covered methods: 482
Total methods: 526
MoreLinq                                    90.7%
Delegating.Delegate                      100.0%
Delegating.DelegatingDisposable           87.5% …

Re-enable tests for hidden extensions on all targets

---

MoreLinq.Test/SortedMergeTest.cs

This PR add `TestSortedMergeDoNotCallMoveNextEagerly`.
Unlike for `Interleave` (#694), this test pass.

SortedMerge: Test do not call MoveNext eagerly

---

.config/dotnet-tools.json

This PR updates [**Meziantou.Framework.NuGetPackageValidation.Tool**](https://www.nuget.org/packages/Meziantou.Framework.NuGetPackageValidation.Tool/) to its [latest version](https://www.nuget.org/packages/Meziantou.Framework.NuGetPackageValidation.Tool/1.0.12). See meziantou/Meziantou.Framework#539 for more background.

Update package validation tool to v1.0.12

---

Directory.Build.props

This PR is a workaround for dotnet/roslyn#41640.

Suppress `EnableGenerateDocumentationFile` warning as workaround for IDE0005

---

MoreLinq.Test/BatchTest.cs
MoreLinq/Batch.cs
MoreLinq/CompatibilitySuppressions.xml
MoreLinq/Extensions.g.cs
MoreLinq/PublicAPI/net6.0/PublicAPI.Unshipped.txt
MoreLinq/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
MoreLinq/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt

Change `Batch` to return arrays

---

MoreLinq/CompatibilitySuppressions.xml
MoreLinq/PublicAPI/net6.0/PublicAPI.Unshipped.txt
MoreLinq/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
MoreLinq/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
MoreLinq/Window.cs
README.md

Remove `Windowed` that's superseded by `Window`

---

MoreLinq.Test/NullArgumentTest.cs
MoreLinq/ToDataTable.cs

Validate `expressions` argument of `ToDataTable`

---

MoreLinq.Test/MaximaTest.cs
MoreLinq.Test/MinimaTest.cs
MoreLinq/Extensions.g.cs
MoreLinq/ExtremaMembers.cs
MoreLinq/MaxBy.cs
MoreLinq/Maxima.cs
MoreLinq/MinBy.cs
MoreLinq/Minima.cs
MoreLinq/MoreLinq.csproj
MoreLinq/PublicAPI/net6.0/PublicAPI.Unshipped.txt
MoreLinq/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
MoreLinq/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
README.md
bld/ExtensionsGenerator/Program.cs

This PR closes #1018.
It introduces `Minima` as a replacement for `MinBy` and `Maxima` as a replacement for `MaxBy`.
`MinBy` and `MaxBy` are still there for compatibility, but marked obsolete. In .NET 6+, they are demoted from being extension methods to regular static ones, which should avoid conflicts with identically named methods introduced with .NET 6. Both methods are, however, exposed as extensions when statically imported via `MoreEnumerable.Extensions.MinByExtension` and `MoreEnumerable.Extensions.MaxByExtension`. These can conflict when a project migrates to .NET 6, but that would have happened anyway. These extensions are also marked as being superseded by their successors and so the developer should be guided to make the required change by using either …

Add `Minima` & `Maxima` as successors to `MinBy` & `MaxBy`

---

MoreLinq.Test/MoreLinq.Test.csproj

This PR removes the [**IsExternalInit**](https://www.nuget.org/packages/IsExternalInit) package reference from the test project that's redundant with [**PolySharp**](https://www.nuget.org/packages/PolySharp).

Remove redundant IsExternalInit package

---

MoreLinq/MoreLinq.csproj

This PR lists the required **[PolySharp]** polyfills explicitly, removing 19 types and with the small benefit of keeping binary/package size stable.
[PolySharp]: https://www.nuget.org/packages/PolySharp

List required PolySharp polyfills explicitly

---

MoreLinq.Test/InterleaveTest.cs
MoreLinq/Interleave.cs

Don't validate content of `otherSequences` argument of `Interleave`

---

MoreLinq.Test/PadStartTest.cs
MoreLinq.Test/PadTest.cs
MoreLinq/Pad.cs
MoreLinq/PadStart.cs

This PR fixes #1027 and #1028.

Fix exception thrown when `Pad`/`PadStart` width is invalid

---

MoreLinq/CompatibilitySuppressions.xml
MoreLinq/MoreLinq.csproj

This PR sets the package validation baseline to the [latest release, 4.0](https://github.com/morelinq/MoreLINQ/releases/tag/v4.0.0) and updates the `CompatibilitySuppressions.xml` file accordingly.

Set package validation baseline to version 4.0

---

MoreLinq/Subsets.cs

This PR addresses the following to-do comment in `Subsets`:
https://github.com/morelinq/MoreLINQ/blob/80ab81c9e06af0409e621ddeef7f83e4f4ebf0b9/MoreLinq/Subsets.cs#L139

Address `Subsets` to-do about clearer members names

---

MoreLinq/RandomSubset.cs
MoreLinq/Shuffle.cs

This PR updates the implementation of `RandomSubsetImpl` to remove the unnecessary closure and DRY the instantiation code.

Refactor `RandomSubset` internals for DRY, removing closure

---

MoreLinq.Test/SubsetTest.cs
MoreLinq/Subsets.cs

This PR refactors the implementation of `Subsets` into a simpler iterator method. As a by-product, it:
- fixes #1047
- removes [redundant allocations](https://github.com/morelinq/MoreLINQ/blob/a263661f61ffc11ecad07f3a6f8fe2418a68f774/MoreLinq/Subsets.cs#L236) when called via `Subsets()` overload

Refactor `Subsets` core into an iterator method

---

MoreLinq.Test/SequenceTest.cs
MoreLinq.Test/ToDataTableTest.cs
MoreLinq.Test/TraceTest.cs
MoreLinq/MoreLinq.csproj

This PR represents preparation for the next release, assuming it will be the minor version 4.2.

Preparation for next release (4.2)

---

.github/workflows/build.yml
.gitignore
appveyor.yml

In addition to AppVeyor, this PR adds a GitHub Action workflow for building the solution with the idea of eventually migrating to it.
What's still missing is e-mail notifications and publishing the package on a dev feed.
See [test run 7593349952 at atifaziz/MoreLINQ](https://github.com/atifaziz/MoreLINQ/actions/runs/7593349952).

Add GitHub Action workflow for building

---

MoreLinq/Experimental/Async/Merge.cs

Fix pending tasks wait loop in async streams `Merge`

---

MoreLinq.Test/AggregateTest.cs
MoreLinq.Test/BacksertTest.cs
MoreLinq.Test/CountDownTest.cs
MoreLinq.Test/EndsWithTest.cs
MoreLinq.Test/Enumerable.cs
MoreLinq.Test/InsertTest.cs
MoreLinq.Test/ReturnTest.cs
MoreLinq.Test/SampleData.cs
MoreLinq.Test/Scope.cs
MoreLinq.Test/StartsWithTest.cs
MoreLinq.Test/TestExtensions.cs
MoreLinq.Test/TraverseTest.cs
MoreLinq/FullGroupJoin.cs
MoreLinq/Maxima.cs
MoreLinq/Partition.cs
MoreLinq/TakeLast.cs
bld/ExtensionsGenerator/Program.cs

This PR addresses the following style warnings/errors:
- [IDE0028: Use primary constructor](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028)
- [IDE0290: Use primary constructor](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0290)
- [IDE0300: Collection initialization can be simplified](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0300)
- [IDE0301: Collection initialization can be simplified](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0301)

Fix style errors: IDE0028, IDE0290, IDE0300 & IDE0301

---

.config/dotnet-tools.json

This PR updates the [Meziantou.Framework.NuGetPackageValidation.Tool](https://www.nuget.org/packages/meziantou.framework.nugetpackagevalidation.tool) package to its [latest version (1.0.14)](https://www.nuget.org/packages/Meziantou.Framework.NuGetPackageValidation.Tool/1.0.14) so that .NET 7 is not required.

Update NuGet package validation tool to latest version

---

.github/workflows/build.yml
MoreLinq.Test/MoreLinq.Test.csproj
appveyor.yml
test.cmd
test.sh

This PR removes testing against [.NET 7](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) (STS), which reaches [end-of-life](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) next week, on May 14, 2024.

Remove testing against .NET 7 (near end-of-life)

---

global.json

This PR pins the solution to .NET SDK 8.0.2xx. Up to now, the roll-forward policy was latest feature, but .NET SDK 8.0.300 introduces a regressions which causes compilation to fail due to the following code analysis errors:
bld\ExtensionsGenerator\obj\Debug\net8.0\DocoptNet\DocoptNet.CodeGeneration.SourceGenerator\ProgramArguments.cs(1,1): error IDE0240: Nullable directive is redundant (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0240)
bld\ExtensionsGenerator\obj\Debug\net8.0\DocoptNet\DocoptNet.CodeGeneration.SourceGenerator\ProgramArguments.cs(45,17): error IDE0010: Populate switch (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0010)
bld\ExtensionsGenerator\obj\Debug\net8.0\DocoptNet\DocoptNet.CodeGeneration.SourceGenerator\ …

Pin to .NET SDK 8.0.2xx

---

MoreLinq.Test.Aot/MoreLinq.Test.Aot.csproj
MoreLinq.Test.Aot/ToDataTableTest.cs
MoreLinq.Test/Throws.cs
MoreLinq.Test/ToDataTableTest.cs
MoreLinq.sln
MoreLinq/Extensions.ToDataTable.g.cs
MoreLinq/MoreLinq.csproj
MoreLinq/ToDataTable.cs
test.cmd
test.sh

This PR enables Native AOT compatibility by supporting trimming. The `ToDataTable` method (and its overloads) is the only one that needed adjusting because it uses reflection internally to list fields and properties of a type when none are given via _quoted lambda expressions_. When _quoted lambda expressions_ are supplied, reflection is used for actual invocation when the runtime does not support dynamic code generation.
[Unit tests have also been added to exercise the compiled and trimmed native AOT code](https://devblogs.microsoft.com/dotnet/testing-your-native-aot-dotnet-apps/).
The PR also introduces a **breaking change** (to improve Native AOT compatibility) where the columns pertaining to public fields will appear before those pertaining to public properties in a `DataTable`. This …

Enable Native AOT compatibility (trimming support)

---

.config/dotnet-tools.json
MoreLinq.Test.Aot/MoreLinq.Test.Aot.csproj
MoreLinq.Test.Aot/ToDataTableTest.cs
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq/MoreLinq.csproj
bld/ExtensionsGenerator/.editorconfig
bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
global.json

This PR updates the solution to use .NET SDK 8.0.400 and updates all dependencies to their latest versions.
It closes #1073 by adding an `.editorconfig` to the **MoreLinq.ExtensionsGenerator** project so style issues are not flagged as warnings, which were appearing in code generated by [docopt.net](https://www.nuget.org/packages/docopt.net).

Update .NET SDK to 8.0.400, including dependencies

---

.github/workflows/build.yml
appveyor.yml

This PR removes building & testing on macOS from CI pipelines.
The macOS machines on CI platforms seems to fail often, adds to the overall CI checks times and brings little benefit. It was historically interesting for testing against Mono on macOS and validating compatibility of tools/binaries used in Bash scripts.
This can always be revived if needed.

Drop CI build matrix & testing on macOS images

---

MoreLinq.Test/TransposeTest.cs
test.sh

This PR drops testing on Mono, which was there for historical reasons when it was the go-to option for running & using .NET Framework assemblies on non-Windows platforms. This changed with .NET (Core), which now runs on many non-Windows platforms. Also:
> Microsoft maintains a modern fork of [Mono runtime in the dotnet/runtime repo](https://github.com/dotnet/runtime/tree/main/src/mono) and has been progressively moving workloads to that fork. That work is now complete, and we recommend that active Mono users and maintainers of Mono-based app frameworks migrate to [.NET](https://github.com/dotnet/core) which includes work from this fork.

Drop conditional testing on Mono

---

MoreLinq/EndsWith.cs

This PR simplifies the implementation of `EndsWith` in the following ways:
- Folds the nested condition.
- Changes the local function (previously `Impl`) to be non-static so its signature can be simpler (it doesn't induce a closure).
- Avoids a closure with `All` by using `SequenceEqual` instead.
- Removes the unnecessary `comparer` initialization, which can be passed as-is to `SequenceEqual`.

Simplify internal implementation details of `EndsWith`

---

MoreLinq.Test/.editorconfig
MoreLinq.Test/AggregateTest.cs
MoreLinq.Test/NullArgumentTest.cs
MoreLinq.Test/OrderedMergeTest.cs
MoreLinq.Test/PadStartTest.cs
MoreLinq.Test/PadTest.cs
MoreLinq.Test/PrependTest.cs
MoreLinq.Test/ReturnTest.cs
MoreLinq.Test/SkipUntilTest.cs
MoreLinq.Test/TrySingleTest.cs
MoreLinq.Test/ZipLongestTest.cs

This PR:
- closes #1024 
- closes #1025

Fix NUnit warnings NUnit1029 & NUnit1030

---

.github/workflows/build.yml
MoreLinq.Test.Aot/MoreLinq.Test.Aot.csproj
MoreLinq.Test.Aot/ToDataTableTest.cs
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.Test/ToDataTableTest.cs
MoreLinq/Experimental/Batch.cs
MoreLinq/MoreLinq.csproj
MoreLinq/ToDataTable.cs
appveyor.yml
bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
build.cmd
build.sh
global.json
test.cmd
test.sh

This PR updates the solution to use .NET SDK 9.0.100 and updates all dependencies to their latest versions.
It also adds .NET 9 testing as a target and updates code needed to compile and run on .NET 9.

Update .NET SDK to 9, including dependencies

---

.devcontainer/README.md
.devcontainer/devcontainer.json
.github/workflows/build.yml
README.md
appveyor.yml

This pull request introduces a dev container setup to ensure a consistent development environment for the project. The main changes include adding a `devcontainer.json` configuration file and updating the documentation to guide developers on using the dev container with Visual Studio Code or GitHub Codespaces.

Add dev container support for development

---

MoreLinq.Test.Aot/ToDataTableTest.cs
MoreLinq.Test/AggregateTest.cs
MoreLinq.Test/BacksertTest.cs
MoreLinq.Test/CartesianTest.cs
MoreLinq.Test/FullGroupJoinTest.cs
MoreLinq.Test/MaximaTest.cs
MoreLinq.Test/MinimaTest.cs
MoreLinq.Test/NullArgumentTest.cs
MoreLinq.Test/PrependTest.cs
MoreLinq.Test/RepeatTest.cs
MoreLinq.Test/SkipUntilTest.cs
MoreLinq.Test/SplitTest.cs
MoreLinq.Test/TestExtensions.cs
MoreLinq.Test/ToDataTableTest.cs
MoreLinq.Test/WindowLeftTest.cs
MoreLinq.Test/WindowRightTest.cs
MoreLinq.Test/ZipLongestTest.cs
MoreLinq/EndsWith.cs
MoreLinq/Experimental/Memoize.cs
MoreLinq/Rank.cs
MoreLinq/SortedMerge.cs
MoreLinq/ToDataTable.cs
bld/ExtensionsGenerator/Program.cs

This PR uses collection expressions to simplify collection initialization:
- [IDE0028](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028)
- [IDE0303](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0303)
- [IDE0305](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0305)
- [IDE0306](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0306)

Simplify collection initialization with expressions

---

.devcontainer/devcontainer.json
MoreLinq.Test.Aot/MoreLinq.Test.Aot.csproj
MoreLinq.Test/MoreLinq.Test.csproj
bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
global.json

This PR updates the solution to use .NET SDK 9.0.200 and updates all system-related dependencies to their latest versions.

Update .NET SDK to 9.0.200, including dependencies

---

MoreLinq.Test/MoreLinq.Test.csproj
bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj

This PR updates all package dependencies to their latest versions.
* Updated **coverlet.collector** from version 6.0.2 to 6.0.4.
* Updated **NUnit** from version 4.3.1 to 4.3.2.
* Updated **NUnit.Analyzers** from version 4.5.0 to 4.6.0.
* Updated **NUnitLite** from version 4.3.1 to 4.3.2.
* Updated **NUnit3TestAdapter** from version 4.6.0 to 5.0.0.
* Updated **Microsoft.CodeAnalysis.CSharp** from version 4.12.0 to 4.13.0.

Update all dependencies to their latest versions

---

.devcontainer/devcontainer.json
MoreLinq.Test/MoreLinq.Test.csproj
MoreLinq.shfbproj
MoreLinq/CompatibilitySuppressions.xml
MoreLinq/MoreLinq.csproj
test.cmd
test.sh

This PR drops the [.NET 6](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) run-time target that's no longer supported. It reached end-of-life on November 12, 2024.

Drop target for .NET 6 that's no longer supported

---

.devcontainer/devcontainer.json
MoreLinq.Test.Aot/MoreLinq.Test.Aot.csproj
MoreLinq.Test/MoreLinq.Test.csproj
bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
global.json

This PR updates the solution to use .NET SDK 9.0.300 and updates all system-related dependencies to their latest versions.

Update .NET SDK to 9.0.300, including dependencies
